service: sls-ws-example
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  tracing:
    apiGateway: false
    lambda: false
  logs:
    restApi: false
    websocket: false

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  connect:
    handler: bin/connect
    events:
      - websocket:
          route: $connect

  echo:
    handler: bin/echo
    events:
      - websocket:
          route: $default

resources:
  Resources:
    routeResponse:
      Type: AWS::ApiGatewayV2::RouteResponse
      Properties:
        ApiId:
          Ref: WebsocketsApi
        RouteId:
          Ref: SdefaultWebsocketsRoute
        RouteResponseKey: $default
